# Generated by build_overrides.py from /home/ubuntu/data/phq_combined.csv
# Tight window = contiguous hours where firing>=65%, settled<=30%, n>=20,
#   mae<=1.3*best_mae. Window endpoints are HOUR BIN boundaries.
# Coverage: 394/480 cells. Gaps: 86 (see comments).
PUSH_WINDOW_OVERRIDES: dict = {
    # --- KATL ---
    ('KATL', 'HIGH',  1): (2.65, -0.65),
    ('KATL', 'HIGH',  2): (1.03, -0.03),
    ('KATL', 'HIGH',  3): (0.78, 0.22),
    ('KATL', 'HIGH',  5): (2.62, -0.62),
    ('KATL', 'HIGH',  7): (3.57, -0.57),
    ('KATL', 'HIGH',  8): (1.62, -0.62),
    ('KATL', 'HIGH',  9): (4.28, -0.28),
    ('KATL', 'HIGH', 10): (2.2, -0.2),
    ('KATL', 'HIGH', 11): (1.28, -0.28),
    ('KATL', 'HIGH', 12): (2.47, -0.47),
    ('KATL', 'LOW',  5): (4.1, -1.1),
    ('KATL', 'LOW',  6): (3.68, -0.68),
    ('KATL', 'LOW',  7): (4.77, -0.77),
    ('KATL', 'LOW',  8): (4.93, -0.93),
    ('KATL', 'LOW',  9): (3.45, -0.45),
    ('KATL', 'LOW', 11): (5.38, -1.38),
    # --- KAUS ---
    ('KAUS', 'HIGH',  1): (1.78, 0.22),
    ('KAUS', 'HIGH',  2): (2.87, -0.87),
    ('KAUS', 'HIGH',  3): (2.52, 0.48),
    ('KAUS', 'HIGH',  4): (1.5, 0.5),
    ('KAUS', 'HIGH',  5): (2.53, -0.53),
    ('KAUS', 'HIGH',  6): (0.72, 0.28),
    ('KAUS', 'HIGH',  7): (0.65, 0.35),
    ('KAUS', 'HIGH',  8): (1.78, 0.22),
    ('KAUS', 'HIGH',  9): (2.38, -0.38),
    ('KAUS', 'HIGH', 10): (1.23, -0.23),
    ('KAUS', 'HIGH', 11): (2.33, -0.33),
    ('KAUS', 'HIGH', 12): (1.27, -0.27),
    ('KAUS', 'LOW',  2): (5.37, -1.37),
    ('KAUS', 'LOW',  3): (4.5, -1.5),
    ('KAUS', 'LOW',  5): (4.38, -1.38),
    ('KAUS', 'LOW',  6): (2.3, -0.3),
    ('KAUS', 'LOW',  7): (2.6, -0.6),
    ('KAUS', 'LOW',  8): (5.0, -1.0),
    ('KAUS', 'LOW',  9): (2.87, 0.13),
    ('KAUS', 'LOW', 10): (4.35, -0.35),
    # --- KBOS ---
    ('KBOS', 'HIGH',  2): (4.03, -0.03),
    ('KBOS', 'HIGH',  3): (2.5, -0.5),
    ('KBOS', 'HIGH',  4): (4.28, -1.28),
    ('KBOS', 'HIGH',  5): (4.4, -1.4),
    ('KBOS', 'HIGH',  7): (3.32, -0.32),
    ('KBOS', 'HIGH',  8): (3.23, -1.23),
    ('KBOS', 'HIGH',  9): (2.87, -0.87),
    ('KBOS', 'HIGH', 11): (4.27, -0.27),
    ('KBOS', 'HIGH', 12): (2.62, -0.62),
    ('KBOS', 'LOW',  2): (4.55, -1.55),
    ('KBOS', 'LOW',  4): (4.32, -1.32),
    ('KBOS', 'LOW',  5): (3.78, -0.78),
    ('KBOS', 'LOW',  6): (3.65, -1.65),
    ('KBOS', 'LOW',  7): (3.88, -0.88),
    ('KBOS', 'LOW',  8): (4.33, -0.33),
    ('KBOS', 'LOW',  9): (4.67, -1.67),
    ('KBOS', 'LOW', 10): (4.88, -0.88),
    # --- KDCA ---
    ('KDCA', 'HIGH',  3): (3.52, -0.52),
    ('KDCA', 'HIGH',  4): (1.7, -0.7),
    ('KDCA', 'HIGH',  5): (2.13, -1.13),
    ('KDCA', 'HIGH',  6): (3.97, 0.03),
    ('KDCA', 'HIGH',  7): (2.02, -0.02),
    ('KDCA', 'HIGH',  8): (2.92, 0.08),
    ('KDCA', 'HIGH',  9): (2.17, -0.17),
    ('KDCA', 'HIGH', 10): (0.83, 0.17),
    ('KDCA', 'HIGH', 11): (3.12, -1.12),
    ('KDCA', 'HIGH', 12): (3.05, -1.05),
    ('KDCA', 'LOW',  1): (5.2, -1.2),
    ('KDCA', 'LOW',  3): (4.18, -2.18),
    ('KDCA', 'LOW',  4): (4.08, -1.08),
    ('KDCA', 'LOW',  5): (4.23, -1.23),
    ('KDCA', 'LOW',  6): (4.15, -0.15),
    ('KDCA', 'LOW',  7): (4.22, -0.22),
    ('KDCA', 'LOW',  8): (4.57, -0.57),
    ('KDCA', 'LOW',  9): (5.03, -1.03),
    ('KDCA', 'LOW', 10): (4.45, -1.45),
    ('KDCA', 'LOW', 11): (5.05, -1.05),
    ('KDCA', 'LOW', 12): (4.5, -1.5),
    # --- KDEN ---
    ('KDEN', 'HIGH',  1): (2.33, -0.33),
    ('KDEN', 'HIGH',  2): (0.77, 0.23),
    ('KDEN', 'HIGH',  4): (1.18, -0.18),
    ('KDEN', 'HIGH',  5): (2.87, -1.87),
    ('KDEN', 'HIGH',  6): (2.12, -0.12),
    ('KDEN', 'HIGH',  7): (2.82, -0.82),
    ('KDEN', 'HIGH',  8): (0.92, 0.08),
    ('KDEN', 'HIGH',  9): (0.93, 0.07),
    ('KDEN', 'HIGH', 10): (0.68, 0.32),
    ('KDEN', 'HIGH', 11): (1.5, -0.5),
    ('KDEN', 'HIGH', 12): (1.23, -0.23),
    ('KDEN', 'LOW',  1): (4.83, -0.83),
    ('KDEN', 'LOW',  2): (4.95, -1.95),
    ('KDEN', 'LOW',  3): (4.97, -0.97),
    ('KDEN', 'LOW',  4): (3.8, -0.8),
    ('KDEN', 'LOW',  6): (4.03, -1.03),
    ('KDEN', 'LOW',  7): (4.05, -0.05),
    ('KDEN', 'LOW',  8): (4.52, -1.52),
    ('KDEN', 'LOW',  9): (4.75, -1.75),
    ('KDEN', 'LOW', 10): (5.15, -2.15),
    ('KDEN', 'LOW', 11): (5.17, -2.17),
    # --- KDFW ---
    ('KDFW', 'HIGH',  2): (0.72, 0.28),
    ('KDFW', 'HIGH',  3): (1.33, -0.33),
    ('KDFW', 'HIGH',  4): (1.48, -0.48),
    ('KDFW', 'HIGH',  5): (2.55, -0.55),
    ('KDFW', 'HIGH',  6): (1.48, -0.48),
    ('KDFW', 'HIGH',  7): (0.65, 0.35),
    ('KDFW', 'HIGH',  8): (0.63, 0.37),
    ('KDFW', 'HIGH',  9): (2.33, 0.67),
    ('KDFW', 'HIGH', 10): (1.2, -0.2),
    ('KDFW', 'HIGH', 11): (2.2, -0.2),
    ('KDFW', 'HIGH', 12): (1.3, -0.3),
    ('KDFW', 'LOW',  2): (5.28, -0.28),
    ('KDFW', 'LOW',  4): (5.22, -1.22),
    ('KDFW', 'LOW',  5): (5.0, -1.0),
    ('KDFW', 'LOW',  6): (3.85, -0.85),
    ('KDFW', 'LOW',  7): (5.17, -0.17),
    ('KDFW', 'LOW',  8): (2.47, -0.47),
    ('KDFW', 'LOW',  9): (5.33, -1.33),
    ('KDFW', 'LOW', 11): (4.22, -1.22),
    ('KDFW', 'LOW', 12): (5.17, -0.17),
    # --- KHOU ---
    ('KHOU', 'HIGH',  1): (3.17, -1.17),
    ('KHOU', 'HIGH',  2): (1.1, -0.1),
    ('KHOU', 'HIGH',  3): (2.65, -0.65),
    ('KHOU', 'HIGH',  5): (2.57, -0.57),
    ('KHOU', 'HIGH',  6): (1.43, -0.43),
    ('KHOU', 'HIGH',  7): (2.83, -0.83),
    ('KHOU', 'HIGH',  8): (0.75, 0.25),
    ('KHOU', 'HIGH',  9): (0.57, 0.43),
    ('KHOU', 'HIGH', 10): (1.58, -0.58),
    ('KHOU', 'HIGH', 11): (1.57, -0.57),
    ('KHOU', 'HIGH', 12): (1.77, 0.23),
    ('KHOU', 'LOW',  2): (2.95, -0.95),
    ('KHOU', 'LOW',  5): (4.08, -2.08),
    ('KHOU', 'LOW',  6): (4.23, -0.23),
    ('KHOU', 'LOW',  7): (4.42, -0.42),
    ('KHOU', 'LOW',  8): (4.58, -1.58),
    ('KHOU', 'LOW',  9): (4.9, -0.9),
    ('KHOU', 'LOW', 10): (5.2, -1.2),
    ('KHOU', 'LOW', 11): (4.43, -2.43),
    ('KHOU', 'LOW', 12): (4.95, -0.95),
    # --- KLAS ---
    ('KLAS', 'HIGH',  1): (1.27, -0.27),
    ('KLAS', 'HIGH',  2): (1.48, -0.48),
    ('KLAS', 'HIGH',  3): (0.92, 0.08),
    ('KLAS', 'HIGH',  4): (1.32, -0.32),
    ('KLAS', 'HIGH',  5): (1.32, -0.32),
    ('KLAS', 'HIGH',  7): (2.1, -0.1),
    ('KLAS', 'HIGH',  8): (1.1, -0.1),
    ('KLAS', 'HIGH',  9): (3.0, 0.0),
    ('KLAS', 'HIGH', 10): (1.02, -0.02),
    ('KLAS', 'HIGH', 11): (0.93, 0.07),
    ('KLAS', 'HIGH', 12): (1.85, 0.15),
    ('KLAS', 'LOW',  1): (4.38, -1.38),
    ('KLAS', 'LOW',  2): (3.37, -0.37),
    ('KLAS', 'LOW',  3): (4.83, 0.17),
    ('KLAS', 'LOW',  4): (0.8, 0.2),
    ('KLAS', 'LOW',  5): (2.45, 0.55),
    ('KLAS', 'LOW',  7): (2.58, 0.42),
    ('KLAS', 'LOW',  8): (4.73, 0.27),
    ('KLAS', 'LOW',  9): (4.9, -0.9),
    ('KLAS', 'LOW', 10): (5.0, 0.0),
    ('KLAS', 'LOW', 11): (4.33, -0.33),
    ('KLAS', 'LOW', 12): (4.47, -0.47),
    # --- KLAX ---
    ('KLAX', 'HIGH',  2): (3.02, -1.02),
    ('KLAX', 'HIGH',  3): (4.22, -0.22),
    ('KLAX', 'HIGH',  5): (1.0, 0.0),
    ('KLAX', 'HIGH',  9): (2.43, -0.43),
    ('KLAX', 'HIGH', 10): (2.55, -0.55),
    ('KLAX', 'HIGH', 12): (4.25, -0.25),
    ('KLAX', 'LOW',  1): (3.97, -0.97),
    ('KLAX', 'LOW',  3): (3.85, -0.85),
    ('KLAX', 'LOW',  4): (2.0, 0.0),
    ('KLAX', 'LOW',  5): (3.47, -1.47),
    ('KLAX', 'LOW',  7): (3.05, -2.05),
    ('KLAX', 'LOW',  8): (3.27, -0.27),
    ('KLAX', 'LOW',  9): (2.85, -1.85),
    ('KLAX', 'LOW', 10): (4.27, -1.27),
    ('KLAX', 'LOW', 11): (1.7, -0.7),
    ('KLAX', 'LOW', 12): (3.75, -0.75),
    # --- KMDW ---
    ('KMDW', 'HIGH',  1): (3.28, -1.28),
    ('KMDW', 'HIGH',  2): (1.8, 0.2),
    ('KMDW', 'HIGH',  3): (3.1, -1.1),
    ('KMDW', 'HIGH',  4): (1.6, -0.6),
    ('KMDW', 'HIGH',  5): (2.5, -1.5),
    ('KMDW', 'HIGH',  6): (2.53, -0.53),
    ('KMDW', 'HIGH',  7): (2.47, -0.47),
    ('KMDW', 'HIGH',  8): (1.2, -0.2),
    ('KMDW', 'HIGH',  9): (1.3, -0.3),
    ('KMDW', 'HIGH', 10): (2.22, -0.22),
    ('KMDW', 'HIGH', 11): (2.35, -0.35),
    ('KMDW', 'HIGH', 12): (3.42, -1.42),
    ('KMDW', 'LOW',  2): (5.25, -2.25),
    ('KMDW', 'LOW',  3): (5.27, -1.27),
    ('KMDW', 'LOW',  4): (4.9, -0.9),
    ('KMDW', 'LOW',  5): (2.22, -0.22),
    ('KMDW', 'LOW',  6): (4.2, -1.2),
    ('KMDW', 'LOW',  7): (4.13, -0.13),
    ('KMDW', 'LOW',  8): (4.35, -0.35),
    ('KMDW', 'LOW',  9): (4.92, -0.92),
    ('KMDW', 'LOW', 10): (5.18, -0.18),
    ('KMDW', 'LOW', 11): (5.17, -1.17),
    # --- KMIA ---
    ('KMIA', 'HIGH',  1): (3.13, -1.13),
    ('KMIA', 'HIGH',  2): (2.97, 0.03),
    ('KMIA', 'HIGH',  3): (3.68, -0.68),
    ('KMIA', 'HIGH',  4): (3.73, 0.27),
    ('KMIA', 'HIGH',  5): (1.55, -0.55),
    ('KMIA', 'HIGH',  6): (4.22, -1.22),
    ('KMIA', 'HIGH',  8): (2.32, -0.32),
    ('KMIA', 'HIGH',  9): (3.2, -0.2),
    ('KMIA', 'HIGH', 11): (3.57, -0.57),
    ('KMIA', 'HIGH', 12): (1.92, 0.08),
    ('KMIA', 'LOW',  2): (3.98, -0.98),
    ('KMIA', 'LOW',  3): (4.28, -0.28),
    ('KMIA', 'LOW',  4): (4.22, -1.22),
    ('KMIA', 'LOW',  5): (2.23, -1.23),
    ('KMIA', 'LOW',  6): (3.98, -1.98),
    ('KMIA', 'LOW',  7): (4.58, -1.58),
    ('KMIA', 'LOW',  8): (4.4, -1.4),
    ('KMIA', 'LOW',  9): (4.32, -1.32),
    ('KMIA', 'LOW', 10): (4.32, -0.32),
    ('KMIA', 'LOW', 11): (4.13, -2.13),
    ('KMIA', 'LOW', 12): (4.3, -1.3),
    # --- KMSP ---
    ('KMSP', 'HIGH',  2): (1.28, -0.28),
    ('KMSP', 'HIGH',  3): (2.1, -1.1),
    ('KMSP', 'HIGH',  4): (1.58, -0.58),
    ('KMSP', 'HIGH',  5): (2.57, -0.57),
    ('KMSP', 'HIGH',  6): (2.52, -0.52),
    ('KMSP', 'HIGH',  8): (3.18, -0.18),
    ('KMSP', 'HIGH',  9): (1.23, -0.23),
    ('KMSP', 'HIGH', 10): (0.85, 0.15),
    ('KMSP', 'HIGH', 11): (0.72, 0.28),
    ('KMSP', 'HIGH', 12): (2.5, -1.5),
    ('KMSP', 'LOW',  4): (5.1, -0.1),
    ('KMSP', 'LOW',  5): (3.68, 0.32),
    ('KMSP', 'LOW',  6): (4.08, -0.08),
    ('KMSP', 'LOW',  7): (4.4, -1.4),
    ('KMSP', 'LOW',  9): (5.18, -0.18),
    ('KMSP', 'LOW', 11): (5.47, -2.47),
    # --- KMSY ---
    ('KMSY', 'HIGH',  1): (3.78, -0.78),
    ('KMSY', 'HIGH',  2): (1.93, 0.07),
    ('KMSY', 'HIGH',  3): (2.43, -0.43),
    ('KMSY', 'HIGH',  4): (4.22, -1.22),
    ('KMSY', 'HIGH',  5): (1.3, -0.3),
    ('KMSY', 'HIGH',  6): (4.12, -1.12),
    ('KMSY', 'HIGH',  8): (1.3, 0.7),
    ('KMSY', 'HIGH', 10): (1.22, -0.22),
    ('KMSY', 'HIGH', 11): (4.43, -0.43),
    ('KMSY', 'HIGH', 12): (2.32, -0.32),
    ('KMSY', 'LOW',  1): (5.02, -1.02),
    ('KMSY', 'LOW',  2): (5.02, -2.02),
    ('KMSY', 'LOW',  3): (4.92, -1.92),
    ('KMSY', 'LOW',  4): (4.3, -1.3),
    ('KMSY', 'LOW',  5): (3.17, -1.17),
    ('KMSY', 'LOW',  6): (3.78, -0.78),
    ('KMSY', 'LOW',  7): (4.28, -1.28),
    ('KMSY', 'LOW',  8): (4.28, -1.28),
    ('KMSY', 'LOW',  9): (2.37, -1.37),
    ('KMSY', 'LOW', 10): (4.92, -0.92),
    ('KMSY', 'LOW', 11): (4.82, -1.82),
    # --- KNYC ---
    ('KNYC', 'HIGH',  3): (3.98, 0.02),
    ('KNYC', 'HIGH',  4): (2.43, -0.43),
    ('KNYC', 'HIGH',  5): (2.97, -0.97),
    ('KNYC', 'HIGH',  6): (4.13, -0.13),
    ('KNYC', 'HIGH',  7): (2.98, 0.02),
    ('KNYC', 'HIGH',  8): (2.82, -0.82),
    ('KNYC', 'HIGH',  9): (0.87, 0.13),
    ('KNYC', 'HIGH', 10): (1.8, -0.8),
    ('KNYC', 'LOW',  2): (4.98, -1.98),
    ('KNYC', 'LOW',  3): (5.05, -2.05),
    ('KNYC', 'LOW',  4): (2.47, -0.47),
    ('KNYC', 'LOW',  5): (2.37, -0.37),
    ('KNYC', 'LOW',  6): (4.33, -0.33),
    ('KNYC', 'LOW',  7): (4.53, -0.53),
    ('KNYC', 'LOW',  8): (3.77, -0.77),
    ('KNYC', 'LOW',  9): (4.85, -0.85),
    ('KNYC', 'LOW', 10): (5.35, -1.35),
    ('KNYC', 'LOW', 11): (5.03, -2.03),
    # --- KOKC ---
    ('KOKC', 'HIGH',  1): (3.6, 0.4),
    ('KOKC', 'HIGH',  2): (3.77, 0.23),
    ('KOKC', 'HIGH',  3): (2.32, -0.32),
    ('KOKC', 'HIGH',  4): (3.47, -0.47),
    ('KOKC', 'HIGH',  5): (2.45, -0.45),
    ('KOKC', 'HIGH',  6): (1.33, -0.33),
    ('KOKC', 'HIGH',  8): (1.43, 0.57),
    ('KOKC', 'HIGH',  9): (2.15, -0.15),
    ('KOKC', 'HIGH', 10): (1.05, -0.05),
    ('KOKC', 'HIGH', 11): (1.0, 0.0),
    ('KOKC', 'HIGH', 12): (2.15, -0.15),
    ('KOKC', 'LOW',  1): (4.87, -0.87),
    ('KOKC', 'LOW',  5): (4.77, -1.77),
    ('KOKC', 'LOW',  6): (4.43, -1.43),
    ('KOKC', 'LOW',  7): (4.83, 0.17),
    ('KOKC', 'LOW',  8): (2.98, 0.02),
    ('KOKC', 'LOW',  9): (5.2, -0.2),
    # --- KPHL ---
    ('KPHL', 'HIGH',  2): (4.43, 0.57),
    ('KPHL', 'HIGH',  3): (2.15, -0.15),
    ('KPHL', 'HIGH',  4): (2.4, -0.4),
    ('KPHL', 'HIGH',  5): (3.23, -0.23),
    ('KPHL', 'HIGH',  6): (3.15, -0.15),
    ('KPHL', 'HIGH',  7): (3.27, -0.27),
    ('KPHL', 'HIGH',  8): (3.03, -0.03),
    ('KPHL', 'HIGH',  9): (0.82, 0.18),
    ('KPHL', 'HIGH', 10): (0.77, 0.23),
    ('KPHL', 'HIGH', 11): (3.73, -0.73),
    ('KPHL', 'LOW',  1): (5.13, -1.13),
    ('KPHL', 'LOW',  2): (4.85, -1.85),
    ('KPHL', 'LOW',  3): (4.9, -0.9),
    ('KPHL', 'LOW',  4): (4.7, -0.7),
    ('KPHL', 'LOW',  5): (3.95, -0.95),
    ('KPHL', 'LOW',  6): (4.0, -1.0),
    ('KPHL', 'LOW',  7): (4.22, -1.22),
    ('KPHL', 'LOW',  8): (4.48, -1.48),
    ('KPHL', 'LOW',  9): (2.9, -0.9),
    ('KPHL', 'LOW', 10): (4.97, 0.03),
    ('KPHL', 'LOW', 11): (5.23, -1.23),
    ('KPHL', 'LOW', 12): (4.68, -1.68),
    # --- KPHX ---
    ('KPHX', 'HIGH',  1): (1.03, -0.03),
    ('KPHX', 'HIGH',  2): (3.97, 0.03),
    ('KPHX', 'HIGH',  3): (2.82, 0.18),
    ('KPHX', 'HIGH',  4): (1.78, 0.22),
    ('KPHX', 'HIGH',  5): (1.7, 0.3),
    ('KPHX', 'HIGH',  6): (2.92, 0.08),
    ('KPHX', 'HIGH',  7): (2.0, 0.0),
    ('KPHX', 'HIGH',  9): (3.55, 0.45),
    ('KPHX', 'HIGH', 10): (2.55, 0.45),
    ('KPHX', 'HIGH', 11): (1.45, -0.45),
    ('KPHX', 'HIGH', 12): (0.67, 0.33),
    ('KPHX', 'LOW',  1): (4.78, -0.78),
    ('KPHX', 'LOW',  2): (3.43, -0.43),
    ('KPHX', 'LOW',  3): (3.93, 0.07),
    ('KPHX', 'LOW',  4): (1.73, 0.27),
    ('KPHX', 'LOW',  5): (1.35, 0.65),
    ('KPHX', 'LOW',  6): (1.27, -0.27),
    ('KPHX', 'LOW',  7): (3.4, -0.4),
    ('KPHX', 'LOW',  8): (1.67, 0.33),
    ('KPHX', 'LOW',  9): (2.77, 0.23),
    ('KPHX', 'LOW', 10): (5.0, 0.0),
    ('KPHX', 'LOW', 11): (4.0, -1.0),
    ('KPHX', 'LOW', 12): (4.28, -0.28),
    # --- KSAT ---
    ('KSAT', 'HIGH',  1): (1.83, 0.17),
    ('KSAT', 'HIGH',  2): (2.02, -0.02),
    ('KSAT', 'HIGH',  3): (0.53, 0.47),
    ('KSAT', 'HIGH',  4): (0.83, 0.17),
    ('KSAT', 'HIGH',  6): (1.88, 0.12),
    ('KSAT', 'HIGH',  7): (1.07, -0.07),
    ('KSAT', 'HIGH',  8): (1.98, 0.02),
    ('KSAT', 'HIGH',  9): (2.5, 0.5),
    ('KSAT', 'HIGH', 11): (2.42, -0.42),
    ('KSAT', 'HIGH', 12): (2.43, -0.43),
    ('KSAT', 'LOW',  1): (5.35, -2.35),
    ('KSAT', 'LOW',  2): (5.18, -1.18),
    ('KSAT', 'LOW',  5): (4.65, -0.65),
    ('KSAT', 'LOW',  6): (3.88, -0.88),
    ('KSAT', 'LOW',  7): (4.52, -1.52),
    ('KSAT', 'LOW',  8): (3.72, 0.28),
    ('KSAT', 'LOW',  9): (3.07, -0.07),
    ('KSAT', 'LOW', 10): (4.18, -0.18),
    ('KSAT', 'LOW', 11): (4.58, -1.58),
    ('KSAT', 'LOW', 12): (5.0, -1.0),
    # --- KSEA ---
    ('KSEA', 'HIGH',  1): (3.85, -0.85),
    ('KSEA', 'HIGH',  2): (3.13, -0.13),
    ('KSEA', 'HIGH',  3): (4.08, -0.08),
    ('KSEA', 'HIGH',  4): (1.42, -0.42),
    ('KSEA', 'HIGH',  5): (1.9, 0.1),
    ('KSEA', 'HIGH',  6): (1.78, -0.78),
    ('KSEA', 'HIGH',  7): (1.25, -0.25),
    ('KSEA', 'HIGH',  8): (1.12, -0.12),
    ('KSEA', 'HIGH',  9): (1.48, -0.48),
    ('KSEA', 'HIGH', 10): (1.77, -0.77),
    ('KSEA', 'HIGH', 12): (3.28, -1.28),
    ('KSEA', 'LOW',  1): (4.62, -1.62),
    ('KSEA', 'LOW',  3): (4.05, -1.05),
    ('KSEA', 'LOW',  4): (1.48, -0.48),
    ('KSEA', 'LOW',  5): (4.12, -0.12),
    ('KSEA', 'LOW',  6): (3.67, -0.67),
    ('KSEA', 'LOW',  7): (4.22, -0.22),
    ('KSEA', 'LOW',  8): (2.6, -0.6),
    ('KSEA', 'LOW',  9): (2.63, -0.63),
    ('KSEA', 'LOW', 10): (4.82, -1.82),
    ('KSEA', 'LOW', 11): (4.9, -1.9),
    ('KSEA', 'LOW', 12): (4.43, -2.43),
    # --- KSFO ---
    ('KSFO', 'HIGH',  5): (1.73, 0.27),
    ('KSFO', 'HIGH',  6): (1.7, -0.7),
    ('KSFO', 'HIGH',  7): (1.03, -0.03),
    ('KSFO', 'HIGH',  8): (1.05, -0.05),
    ('KSFO', 'HIGH',  9): (1.08, -0.08),
    ('KSFO', 'HIGH', 10): (2.25, -0.25),
    ('KSFO', 'HIGH', 11): (3.3, -0.3),
    ('KSFO', 'LOW',  1): (2.93, 0.07),
    ('KSFO', 'LOW',  2): (3.15, -0.15),
    ('KSFO', 'LOW',  3): (4.35, -0.35),
    ('KSFO', 'LOW',  4): (4.08, -0.08),
    ('KSFO', 'LOW',  5): (3.37, -1.37),
    ('KSFO', 'LOW',  6): (3.33, -0.33),
    ('KSFO', 'LOW',  7): (3.05, -1.05),
    ('KSFO', 'LOW',  8): (2.95, -0.95),
    ('KSFO', 'LOW',  9): (2.95, -0.95),
    ('KSFO', 'LOW', 10): (3.87, 0.13),
    ('KSFO', 'LOW', 11): (2.95, -0.95),
    ('KSFO', 'LOW', 12): (3.08, -1.08),
}

# Cells without override (fall back to global PUSH_PEAK_HOURS_*):
#   KATL LOW  mo= 1  reason=out_of_bounds before=5.95 after=-0.95 width=5.0
#   KATL LOW  mo= 2  reason=out_of_bounds before=5.68 after=-0.68 width=5.0
#   KATL LOW  mo= 3  reason=out_of_bounds before=5.93 after=-0.93 width=5.0
#   KATL HIGH mo= 4  reason=out_of_bounds before=1.9 after=-0.9 width=1.0
#   KATL LOW  mo= 4  reason=out_of_bounds before=5.55 after=-1.55 width=4.0
#   KATL HIGH mo= 6  reason=out_of_bounds before=7.58 after=-6.58 width=1.0
#   KATL LOW  mo=10  reason=out_of_bounds before=5.77 after=-0.77 width=5.0
#   KATL LOW  mo=12  reason=out_of_bounds before=5.67 after=-1.67 width=4.0
#   KAUS LOW  mo= 1  reason=out_of_bounds before=6.02 after=-1.02 width=5.0
#   KAUS LOW  mo= 4  reason=out_of_bounds before=4.8 after=-2.8 width=2.0
#   KAUS LOW  mo=11  reason=out_of_bounds before=4.78 after=-2.78 width=2.0
#   KAUS LOW  mo=12  reason=out_of_bounds before=5.57 after=-1.57 width=4.0
#   KBOS HIGH mo= 1  reason=out_of_bounds before=5.78 after=0.22 width=6.0
#   KBOS LOW  mo= 1  reason=out_of_bounds before=5.77 after=-1.77 width=4.0
#   KBOS LOW  mo= 3  reason=out_of_bounds before=4.73 after=-2.73 width=2.0
#   KBOS HIGH mo= 6  reason=out_of_bounds before=2.32 after=-1.32 width=1.0
#   KBOS HIGH mo=10  reason=out_of_bounds before=1.92 after=-0.92 width=1.0
#   KBOS LOW  mo=11  reason=out_of_bounds before=5.1 after=-3.1 width=2.0
#   KBOS LOW  mo=12  reason=out_of_bounds before=5.53 after=-2.53 width=3.0
#   KDCA HIGH mo= 1  reason=out_of_bounds before=5.1 after=-1.1 width=4.0
#   KDCA HIGH mo= 2  reason=out_of_bounds before=4.97 after=-1.97 width=3.0
#   KDCA LOW  mo= 2  reason=no_qualifying_window
#   KDEN HIGH mo= 3  reason=out_of_bounds before=1.88 after=-0.88 width=1.0
#   KDEN LOW  mo= 5  reason=no_qualifying_window
#   KDEN LOW  mo=12  reason=out_of_bounds before=5.67 after=-1.67 width=4.0
#   KDFW HIGH mo= 1  reason=out_of_bounds before=1.68 after=-0.68 width=1.0
#   KDFW LOW  mo= 1  reason=out_of_bounds before=5.6 after=-1.6 width=4.0
#   KDFW LOW  mo= 3  reason=out_of_bounds before=5.58 after=-1.58 width=4.0
#   KDFW LOW  mo=10  reason=out_of_bounds before=5.9 after=-0.9 width=5.0
#   KHOU LOW  mo= 1  reason=out_of_bounds before=5.62 after=-1.62 width=4.0
#   KHOU LOW  mo= 3  reason=out_of_bounds before=4.8 after=-2.8 width=2.0
#   KHOU HIGH mo= 4  reason=out_of_bounds before=1.67 after=-0.67 width=1.0
#   KHOU LOW  mo= 4  reason=out_of_bounds before=4.62 after=-2.62 width=2.0
#   KLAS HIGH mo= 6  reason=out_of_bounds before=7.43 after=-4.43 width=3.0
#   KLAS LOW  mo= 6  reason=out_of_bounds before=1.38 after=-0.38 width=1.0
#   KLAX HIGH mo= 1  reason=out_of_bounds before=0.43 after=0.57 width=1.0
#   KLAX LOW  mo= 2  reason=out_of_bounds before=2.03 after=-1.03 width=1.0
#   KLAX HIGH mo= 4  reason=out_of_bounds before=4.58 after=-0.58 width=4.0
#   KLAX HIGH mo= 6  reason=out_of_bounds before=4.9 after=0.1 width=5.0
#   KLAX LOW  mo= 6  reason=out_of_bounds before=2.3 after=-1.3 width=1.0
#   KLAX HIGH mo= 7  reason=out_of_bounds before=6.83 after=-0.83 width=6.0
#   KLAX HIGH mo= 8  reason=out_of_bounds before=5.78 after=-0.78 width=5.0
#   KLAX HIGH mo=11  reason=out_of_bounds before=3.78 after=-2.78 width=1.0
#   KMDW LOW  mo= 1  reason=out_of_bounds before=5.38 after=-4.38 width=1.0
#   KMDW LOW  mo=12  reason=out_of_bounds before=5.67 after=-1.67 width=4.0
#   KMIA LOW  mo= 1  reason=out_of_bounds before=4.77 after=-2.77 width=2.0
#   KMIA HIGH mo= 7  reason=out_of_bounds before=1.65 after=-0.65 width=1.0
#   KMIA HIGH mo=10  reason=out_of_bounds before=1.4 after=-0.4 width=1.0
#   KMSP HIGH mo= 1  reason=out_of_bounds before=4.27 after=-2.27 width=2.0
#   KMSP LOW  mo= 1  reason=out_of_bounds before=5.88 after=-0.88 width=5.0
#   KMSP LOW  mo= 2  reason=out_of_bounds before=5.7 after=-1.7 width=4.0
#   KMSP LOW  mo= 3  reason=out_of_bounds before=5.62 after=-0.62 width=5.0
#   KMSP HIGH mo= 7  reason=out_of_bounds before=1.38 after=-0.38 width=1.0
#   KMSP LOW  mo= 8  reason=out_of_bounds before=3.68 after=-2.68 width=1.0
#   KMSP LOW  mo=10  reason=out_of_bounds before=5.92 after=-0.92 width=5.0
#   KMSP LOW  mo=12  reason=out_of_bounds before=5.8 after=-3.8 width=2.0
#   KMSY HIGH mo= 7  reason=out_of_bounds before=2.07 after=-1.07 width=1.0
#   KMSY HIGH mo= 9  reason=out_of_bounds before=0.4 after=0.6 width=1.0
#   KMSY LOW  mo=12  reason=out_of_bounds before=4.72 after=-2.72 width=2.0
#   KNYC HIGH mo= 1  reason=out_of_bounds before=6.02 after=-2.02 width=4.0
#   KNYC LOW  mo= 1  reason=out_of_bounds before=5.05 after=-3.05 width=2.0
#   KNYC HIGH mo= 2  reason=out_of_bounds before=4.93 after=-0.93 width=4.0
#   KNYC HIGH mo=11  reason=out_of_bounds before=6.75 after=-0.75 width=6.0
#   KNYC HIGH mo=12  reason=out_of_bounds before=7.13 after=-0.13 width=7.0
#   KNYC LOW  mo=12  reason=out_of_bounds before=5.52 after=-0.52 width=5.0
#   KOKC LOW  mo= 2  reason=out_of_bounds before=5.55 after=-0.55 width=5.0
#   KOKC LOW  mo= 3  reason=out_of_bounds before=5.67 after=-0.67 width=5.0
#   KOKC LOW  mo= 4  reason=out_of_bounds before=5.55 after=-1.55 width=4.0
#   KOKC HIGH mo= 7  reason=out_of_bounds before=5.33 after=-0.33 width=5.0
#   KOKC LOW  mo=10  reason=out_of_bounds before=5.97 after=-0.97 width=5.0
#   KOKC LOW  mo=11  reason=out_of_bounds before=5.52 after=-0.52 width=5.0
#   KOKC LOW  mo=12  reason=out_of_bounds before=5.83 after=-2.83 width=3.0
#   KPHL HIGH mo= 1  reason=out_of_bounds before=4.97 after=-1.97 width=3.0
#   KPHL HIGH mo=12  reason=out_of_bounds before=4.83 after=-0.83 width=4.0
#   KPHX HIGH mo= 8  reason=out_of_bounds before=5.87 after=-3.87 width=2.0
#   KSAT LOW  mo= 3  reason=out_of_bounds before=4.8 after=-2.8 width=2.0
#   KSAT LOW  mo= 4  reason=out_of_bounds before=4.72 after=-2.72 width=2.0
#   KSAT HIGH mo= 5  reason=out_of_bounds before=1.65 after=-0.65 width=1.0
#   KSAT HIGH mo=10  reason=out_of_bounds before=0.48 after=0.52 width=1.0
#   KSEA LOW  mo= 2  reason=out_of_bounds before=4.72 after=-3.72 width=1.0
#   KSEA HIGH mo=11  reason=out_of_bounds before=5.55 after=-0.55 width=5.0
#   KSFO HIGH mo= 1  reason=out_of_bounds before=7.37 after=-0.37 width=7.0
#   KSFO HIGH mo= 2  reason=out_of_bounds before=5.4 after=-0.4 width=5.0
#   KSFO HIGH mo= 3  reason=out_of_bounds before=5.28 after=-0.28 width=5.0
#   KSFO HIGH mo= 4  reason=out_of_bounds before=4.88 after=0.12 width=5.0
#   KSFO HIGH mo=12  reason=out_of_bounds before=6.32 after=-0.32 width=6.0
