# Generated by build_overrides_accuracy.py
# Accuracy-first: lowest mae_pre_peak offset is the anchor.
# Tight window: contiguous offsets with mae_pre_peak <= 1.15 * best_mae
# Filters: firing >= 65%, n_fired_pre >= 20, settled < 100%
# Source: phq_offset_combined.csv (5000-day, 0.5h offset grid)
# Coverage: 424/480 cells. Gaps: 56.
PUSH_WINDOW_OVERRIDES: dict = {
    # --- KATL ---
    ('KATL', 'HIGH',  1): (1.0, 0.0),
    ('KATL', 'HIGH',  2): (1.0, 0.0),
    ('KATL', 'HIGH',  3): (1.5, 0.0),
    ('KATL', 'HIGH',  4): (1.5, 0.0),
    ('KATL', 'HIGH',  5): (1.0, -0.5),
    ('KATL', 'HIGH',  6): (1.5, 0.0),
    ('KATL', 'HIGH',  7): (1.5, 0.0),
    ('KATL', 'HIGH',  8): (1.5, 0.0),
    ('KATL', 'HIGH',  9): (2.0, 0.0),
    ('KATL', 'HIGH', 10): (1.0, -0.5),
    ('KATL', 'HIGH', 11): (1.0, 0.0),
    ('KATL', 'HIGH', 12): (1.0, 0.5),
    ('KATL', 'LOW',  1): (4.0, -0.5),
    ('KATL', 'LOW',  2): (4.0, 0.0),
    ('KATL', 'LOW',  3): (3.5, 0.0),
    ('KATL', 'LOW',  4): (3.0, 0.0),
    ('KATL', 'LOW',  5): (1.5, 0.5),
    ('KATL', 'LOW',  6): (2.0, 0.0),
    ('KATL', 'LOW',  7): (3.0, 0.0),
    ('KATL', 'LOW',  8): (2.0, 1.0),
    ('KATL', 'LOW',  9): (2.0, 0.5),
    ('KATL', 'LOW', 10): (3.0, 0.0),
    ('KATL', 'LOW', 11): (4.0, -0.5),
    ('KATL', 'LOW', 12): (4.0, 0.5),
    # --- KAUS ---
    ('KAUS', 'HIGH',  1): (0.5, 0.5),
    ('KAUS', 'HIGH',  2): (0.5, 0.5),
    ('KAUS', 'HIGH',  4): (1.0, 1.0),
    ('KAUS', 'HIGH',  5): (1.0, -0.5),
    ('KAUS', 'HIGH',  7): (1.0, 0.0),
    ('KAUS', 'HIGH',  8): (1.0, -0.5),
    ('KAUS', 'HIGH', 10): (1.0, 1.0),
    ('KAUS', 'HIGH', 11): (1.0, 0.5),
    ('KAUS', 'HIGH', 12): (0.5, 1.0),
    ('KAUS', 'LOW',  1): (4.0, 1.0),
    ('KAUS', 'LOW',  2): (4.0, 1.0),
    ('KAUS', 'LOW',  3): (4.0, 1.0),
    ('KAUS', 'LOW',  4): (3.0, 1.0),
    ('KAUS', 'LOW',  5): (4.0, 0.5),
    ('KAUS', 'LOW',  6): (1.5, 0.5),
    ('KAUS', 'LOW',  7): (0.5, 0.5),
    ('KAUS', 'LOW',  8): (2.0, 0.5),
    ('KAUS', 'LOW',  9): (3.0, 0.0),
    ('KAUS', 'LOW', 10): (3.5, 0.5),
    ('KAUS', 'LOW', 11): (4.0, 0.5),
    ('KAUS', 'LOW', 12): (4.0, 1.0),
    # --- KBOS ---
    ('KBOS', 'HIGH',  1): (3.0, -0.5),
    ('KBOS', 'HIGH',  2): (3.0, -0.5),
    ('KBOS', 'HIGH',  3): (2.0, 0.0),
    ('KBOS', 'HIGH',  4): (2.5, 0.0),
    ('KBOS', 'HIGH',  5): (2.0, -1.0),
    ('KBOS', 'HIGH',  6): (2.0, -0.5),
    ('KBOS', 'HIGH',  7): (2.0, -0.5),
    ('KBOS', 'HIGH',  8): (1.5, -0.5),
    ('KBOS', 'HIGH',  9): (1.0, 0.0),
    ('KBOS', 'HIGH', 10): (1.0, 0.0),
    ('KBOS', 'HIGH', 11): (2.5, 0.0),
    ('KBOS', 'HIGH', 12): (3.0, 0.0),
    ('KBOS', 'LOW',  1): (4.0, 0.0),
    ('KBOS', 'LOW',  2): (4.0, 0.0),
    ('KBOS', 'LOW',  3): (4.0, 0.5),
    ('KBOS', 'LOW',  4): (3.5, 1.0),
    ('KBOS', 'LOW',  5): (3.5, 0.0),
    ('KBOS', 'LOW',  6): (3.0, 0.0),
    ('KBOS', 'LOW',  7): (3.5, 0.0),
    ('KBOS', 'LOW',  8): (4.0, 0.0),
    ('KBOS', 'LOW',  9): (4.0, 0.0),
    ('KBOS', 'LOW', 10): (4.0, 0.0),
    ('KBOS', 'LOW', 11): (4.0, -0.5),
    ('KBOS', 'LOW', 12): (4.0, 1.0),
    # --- KDCA ---
    ('KDCA', 'HIGH',  1): (3.0, 0.0),
    ('KDCA', 'HIGH',  2): (2.0, 0.5),
    ('KDCA', 'HIGH',  3): (1.5, 0.0),
    ('KDCA', 'HIGH',  4): (1.0, 0.5),
    ('KDCA', 'HIGH',  5): (1.0, 1.0),
    ('KDCA', 'HIGH',  6): (1.0, 0.0),
    ('KDCA', 'HIGH',  7): (1.0, -0.5),
    ('KDCA', 'HIGH',  8): (1.5, -0.5),
    ('KDCA', 'HIGH',  9): (0.5, 0.0),
    ('KDCA', 'HIGH', 10): (1.0, 0.0),
    ('KDCA', 'HIGH', 11): (1.5, 0.0),
    ('KDCA', 'HIGH', 12): (1.5, 0.0),
    ('KDCA', 'LOW',  1): (4.0, 0.0),
    ('KDCA', 'LOW',  2): (4.0, -0.5),
    ('KDCA', 'LOW',  3): (4.0, -1.0),
    ('KDCA', 'LOW',  4): (4.0, -0.5),
    ('KDCA', 'LOW',  5): (4.0, 0.0),
    ('KDCA', 'LOW',  6): (3.0, -0.5),
    ('KDCA', 'LOW',  7): (2.0, 0.0),
    ('KDCA', 'LOW',  8): (2.5, -0.5),
    ('KDCA', 'LOW',  9): (4.0, -0.5),
    ('KDCA', 'LOW', 10): (3.5, 0.0),
    ('KDCA', 'LOW', 11): (4.0, -0.5),
    ('KDCA', 'LOW', 12): (3.5, 0.0),
    # --- KDEN ---
    ('KDEN', 'HIGH',  1): (1.0, -0.5),
    ('KDEN', 'HIGH',  2): (1.0, -0.5),
    ('KDEN', 'HIGH',  3): (1.0, -0.5),
    ('KDEN', 'HIGH',  4): (1.0, -0.5),
    ('KDEN', 'HIGH',  5): (0.5, 0.5),
    ('KDEN', 'HIGH',  6): (1.0, -0.5),
    ('KDEN', 'HIGH',  9): (1.0, -0.5),
    ('KDEN', 'HIGH', 10): (1.0, -0.5),
    ('KDEN', 'HIGH', 11): (1.0, 0.5),
    ('KDEN', 'HIGH', 12): (1.0, 0.0),
    ('KDEN', 'LOW',  1): (4.0, 1.0),
    ('KDEN', 'LOW',  2): (4.0, 0.5),
    ('KDEN', 'LOW',  3): (3.0, 0.5),
    ('KDEN', 'LOW',  4): (2.5, 0.0),
    ('KDEN', 'LOW',  5): (2.0, 0.5),
    ('KDEN', 'LOW',  6): (2.5, 0.5),
    ('KDEN', 'LOW',  7): (2.0, 0.5),
    ('KDEN', 'LOW',  8): (1.0, 1.0),
    ('KDEN', 'LOW',  9): (2.0, 1.0),
    ('KDEN', 'LOW', 10): (4.0, 1.0),
    ('KDEN', 'LOW', 11): (4.0, 0.5),
    ('KDEN', 'LOW', 12): (4.0, -0.5),
    # --- KDFW ---
    ('KDFW', 'HIGH',  1): (0.5, 1.0),
    ('KDFW', 'HIGH',  4): (0.5, 1.0),
    ('KDFW', 'HIGH',  5): (0.5, 0.0),
    ('KDFW', 'HIGH',  6): (1.0, 1.0),
    ('KDFW', 'HIGH',  7): (1.0, -0.5),
    ('KDFW', 'HIGH',  8): (1.0, -0.5),
    ('KDFW', 'HIGH',  9): (1.0, 1.0),
    ('KDFW', 'LOW',  1): (4.0, 0.0),
    ('KDFW', 'LOW',  2): (3.5, 0.5),
    ('KDFW', 'LOW',  3): (4.0, -0.5),
    ('KDFW', 'LOW',  4): (4.0, 0.0),
    ('KDFW', 'LOW',  5): (3.0, 0.5),
    ('KDFW', 'LOW',  6): (3.0, 0.0),
    ('KDFW', 'LOW',  7): (1.5, 0.0),
    ('KDFW', 'LOW',  8): (1.5, 0.0),
    ('KDFW', 'LOW',  9): (2.5, 0.0),
    ('KDFW', 'LOW', 10): (3.5, 0.0),
    ('KDFW', 'LOW', 11): (3.5, 0.0),
    ('KDFW', 'LOW', 12): (3.5, 0.5),
    # --- KHOU ---
    ('KHOU', 'HIGH',  1): (1.5, 0.0),
    ('KHOU', 'HIGH',  2): (1.5, -0.5),
    ('KHOU', 'HIGH',  3): (1.5, 1.0),
    ('KHOU', 'HIGH',  4): (1.0, 0.0),
    ('KHOU', 'HIGH',  5): (1.5, -0.5),
    ('KHOU', 'HIGH',  6): (1.0, -0.5),
    ('KHOU', 'HIGH',  7): (1.5, 1.0),
    ('KHOU', 'HIGH',  8): (1.0, 0.0),
    ('KHOU', 'HIGH',  9): (1.5, 1.0),
    ('KHOU', 'HIGH', 10): (1.0, -0.5),
    ('KHOU', 'HIGH', 11): (1.0, 0.0),
    ('KHOU', 'HIGH', 12): (1.0, 0.5),
    ('KHOU', 'LOW',  1): (4.0, -1.5),
    ('KHOU', 'LOW',  2): (4.0, 0.5),
    ('KHOU', 'LOW',  3): (4.0, 0.0),
    ('KHOU', 'LOW',  4): (3.5, 1.0),
    ('KHOU', 'LOW',  5): (3.0, 0.0),
    ('KHOU', 'LOW',  6): (2.0, -0.5),
    ('KHOU', 'LOW',  7): (3.5, -0.5),
    ('KHOU', 'LOW',  8): (3.5, 0.5),
    ('KHOU', 'LOW',  9): (4.0, 0.5),
    ('KHOU', 'LOW', 10): (4.0, 0.5),
    ('KHOU', 'LOW', 11): (3.5, -0.5),
    ('KHOU', 'LOW', 12): (4.0, -0.5),
    # --- KLAS ---
    ('KLAS', 'HIGH',  1): (1.0, 0.0),
    ('KLAS', 'HIGH',  2): (1.0, 0.0),
    ('KLAS', 'HIGH',  6): (0.5, 0.0),
    ('KLAS', 'HIGH',  7): (1.5, -0.5),
    ('KLAS', 'HIGH',  8): (1.0, -0.5),
    ('KLAS', 'HIGH',  9): (1.0, -0.5),
    ('KLAS', 'HIGH', 10): (0.5, 1.0),
    ('KLAS', 'HIGH', 11): (-0.0, 0.5),
    ('KLAS', 'HIGH', 12): (1.0, 0.0),
    ('KLAS', 'LOW',  1): (2.0, 1.0),
    ('KLAS', 'LOW',  2): (2.0, 0.0),
    ('KLAS', 'LOW',  3): (4.0, -0.5),
    ('KLAS', 'LOW',  4): (2.5, 0.0),
    ('KLAS', 'LOW',  5): (1.5, 0.0),
    ('KLAS', 'LOW',  6): (1.0, 0.0),
    ('KLAS', 'LOW',  7): (2.0, -0.5),
    ('KLAS', 'LOW',  8): (1.5, 0.0),
    ('KLAS', 'LOW',  9): (1.5, 0.0),
    ('KLAS', 'LOW', 10): (2.5, 0.0),
    ('KLAS', 'LOW', 11): (2.0, 0.5),
    ('KLAS', 'LOW', 12): (3.5, 1.0),
    # --- KLAX ---
    ('KLAX', 'HIGH',  1): (1.0, 0.0),
    ('KLAX', 'HIGH',  3): (-0.0, 1.0),
    ('KLAX', 'HIGH',  4): (1.0, 1.0),
    ('KLAX', 'HIGH',  5): (1.5, -0.5),
    ('KLAX', 'HIGH',  6): (2.0, -0.5),
    ('KLAX', 'HIGH',  7): (1.0, -0.5),
    ('KLAX', 'HIGH',  8): (1.5, -0.5),
    ('KLAX', 'HIGH',  9): (1.0, 0.0),
    ('KLAX', 'HIGH', 10): (0.5, 0.0),
    ('KLAX', 'HIGH', 12): (1.0, 0.5),
    ('KLAX', 'LOW',  1): (2.5, 0.5),
    ('KLAX', 'LOW',  2): (3.0, -1.0),
    ('KLAX', 'LOW',  4): (3.0, -0.5),
    ('KLAX', 'LOW',  6): (2.5, -2.0),
    ('KLAX', 'LOW',  7): (2.5, 0.0),
    ('KLAX', 'LOW',  8): (2.5, 0.5),
    ('KLAX', 'LOW',  9): (1.0, 0.5),
    ('KLAX', 'LOW', 10): (2.5, 0.5),
    ('KLAX', 'LOW', 11): (2.0, 0.5),
    ('KLAX', 'LOW', 12): (2.0, 1.0),
    # --- KMDW ---
    ('KMDW', 'HIGH',  1): (1.0, 1.0),
    ('KMDW', 'HIGH',  2): (1.0, 1.0),
    ('KMDW', 'HIGH',  8): (1.0, 1.0),
    ('KMDW', 'HIGH',  9): (1.0, 1.0),
    ('KMDW', 'HIGH', 11): (-0.0, 1.0),
    ('KMDW', 'HIGH', 12): (1.0, 1.0),
    ('KMDW', 'LOW',  1): (4.0, 1.0),
    ('KMDW', 'LOW',  2): (4.0, 0.0),
    ('KMDW', 'LOW',  3): (4.0, 0.0),
    ('KMDW', 'LOW',  4): (4.0, -0.5),
    ('KMDW', 'LOW',  5): (3.5, -0.5),
    ('KMDW', 'LOW',  6): (4.0, -0.5),
    ('KMDW', 'LOW',  7): (2.0, 0.0),
    ('KMDW', 'LOW',  8): (3.0, -0.5),
    ('KMDW', 'LOW',  9): (4.0, 0.0),
    ('KMDW', 'LOW', 10): (4.0, 0.0),
    ('KMDW', 'LOW', 11): (4.0, -0.5),
    ('KMDW', 'LOW', 12): (4.0, 0.5),
    # --- KMIA ---
    ('KMIA', 'HIGH',  1): (1.5, -0.5),
    ('KMIA', 'HIGH',  2): (1.5, -0.5),
    ('KMIA', 'HIGH',  3): (1.5, -0.5),
    ('KMIA', 'HIGH',  4): (1.5, -0.5),
    ('KMIA', 'HIGH',  5): (1.5, 0.0),
    ('KMIA', 'HIGH',  6): (2.0, -0.5),
    ('KMIA', 'HIGH',  7): (1.0, 0.0),
    ('KMIA', 'HIGH',  8): (1.5, 0.0),
    ('KMIA', 'HIGH',  9): (1.0, 0.0),
    ('KMIA', 'HIGH', 10): (1.0, 0.0),
    ('KMIA', 'HIGH', 11): (1.5, 1.0),
    ('KMIA', 'HIGH', 12): (1.5, 1.0),
    ('KMIA', 'LOW',  1): (4.0, 0.5),
    ('KMIA', 'LOW',  2): (3.5, 0.0),
    ('KMIA', 'LOW',  3): (3.5, 0.0),
    ('KMIA', 'LOW',  4): (3.0, 0.0),
    ('KMIA', 'LOW',  5): (3.0, 0.0),
    ('KMIA', 'LOW',  6): (3.5, 1.0),
    ('KMIA', 'LOW',  7): (4.0, 0.0),
    ('KMIA', 'LOW',  8): (4.0, 0.0),
    ('KMIA', 'LOW',  9): (2.5, 1.0),
    ('KMIA', 'LOW', 10): (3.0, 1.0),
    ('KMIA', 'LOW', 11): (3.5, 0.0),
    ('KMIA', 'LOW', 12): (4.0, -1.5),
    # --- KMSP ---
    ('KMSP', 'HIGH',  1): (1.0, 0.5),
    ('KMSP', 'HIGH',  3): (1.0, 1.0),
    ('KMSP', 'HIGH',  7): (0.5, 0.0),
    ('KMSP', 'HIGH',  8): (1.0, 0.0),
    ('KMSP', 'HIGH', 11): (-0.0, 1.0),
    ('KMSP', 'HIGH', 12): (0.5, 1.0),
    ('KMSP', 'LOW',  1): (4.0, 0.5),
    ('KMSP', 'LOW',  2): (4.0, -0.5),
    ('KMSP', 'LOW',  3): (4.0, -0.5),
    ('KMSP', 'LOW',  4): (3.5, 0.0),
    ('KMSP', 'LOW',  5): (2.5, -0.5),
    ('KMSP', 'LOW',  6): (2.5, -0.5),
    ('KMSP', 'LOW',  7): (2.0, 0.0),
    ('KMSP', 'LOW',  9): (3.0, 0.0),
    ('KMSP', 'LOW', 10): (4.0, 0.0),
    ('KMSP', 'LOW', 11): (4.0, 0.0),
    ('KMSP', 'LOW', 12): (4.0, 1.0),
    # --- KMSY ---
    ('KMSY', 'HIGH',  1): (2.0, 1.0),
    ('KMSY', 'HIGH',  2): (1.0, -0.5),
    ('KMSY', 'HIGH',  3): (1.5, 1.0),
    ('KMSY', 'HIGH',  4): (1.5, 0.0),
    ('KMSY', 'HIGH',  7): (0.5, 1.0),
    ('KMSY', 'HIGH',  8): (1.0, -0.5),
    ('KMSY', 'HIGH', 11): (1.5, 1.0),
    ('KMSY', 'HIGH', 12): (1.5, 1.0),
    ('KMSY', 'LOW',  1): (4.0, 0.0),
    ('KMSY', 'LOW',  2): (3.5, 1.0),
    ('KMSY', 'LOW',  3): (3.5, 1.0),
    ('KMSY', 'LOW',  4): (3.5, 0.0),
    ('KMSY', 'LOW',  5): (3.5, 0.0),
    ('KMSY', 'LOW',  6): (3.0, -0.5),
    ('KMSY', 'LOW',  7): (3.5, 0.0),
    ('KMSY', 'LOW',  8): (3.5, 1.0),
    ('KMSY', 'LOW',  9): (4.0, 0.5),
    ('KMSY', 'LOW', 10): (4.0, 1.0),
    ('KMSY', 'LOW', 11): (4.0, 0.5),
    ('KMSY', 'LOW', 12): (3.0, 1.0),
    # --- KNYC ---
    ('KNYC', 'HIGH',  1): (2.5, 1.0),
    ('KNYC', 'HIGH',  2): (2.0, 0.5),
    ('KNYC', 'HIGH',  3): (1.5, -1.0),
    ('KNYC', 'HIGH',  4): (1.0, 0.0),
    ('KNYC', 'HIGH',  5): (1.0, 1.0),
    ('KNYC', 'HIGH',  6): (1.0, -0.5),
    ('KNYC', 'HIGH',  7): (1.0, 0.0),
    ('KNYC', 'HIGH', 11): (1.5, 0.5),
    ('KNYC', 'HIGH', 12): (1.0, 1.0),
    ('KNYC', 'LOW',  1): (4.0, -1.0),
    ('KNYC', 'LOW',  2): (4.0, -0.5),
    ('KNYC', 'LOW',  3): (4.0, 0.0),
    ('KNYC', 'LOW',  4): (4.0, -0.5),
    ('KNYC', 'LOW',  5): (4.0, 0.0),
    ('KNYC', 'LOW',  6): (4.0, -0.5),
    ('KNYC', 'LOW',  7): (3.5, 0.5),
    ('KNYC', 'LOW',  8): (2.0, 0.5),
    ('KNYC', 'LOW',  9): (4.0, -0.5),
    ('KNYC', 'LOW', 10): (3.5, 0.5),
    ('KNYC', 'LOW', 11): (3.5, 0.0),
    ('KNYC', 'LOW', 12): (4.0, -1.0),
    # --- KOKC ---
    ('KOKC', 'HIGH',  1): (1.0, 0.0),
    ('KOKC', 'HIGH',  2): (-0.0, 0.5),
    ('KOKC', 'HIGH',  4): (1.0, -0.5),
    ('KOKC', 'HIGH',  5): (1.5, 1.0),
    ('KOKC', 'HIGH',  6): (0.5, 0.0),
    ('KOKC', 'HIGH',  7): (1.5, -0.5),
    ('KOKC', 'HIGH',  9): (1.0, 1.0),
    ('KOKC', 'HIGH', 11): (-0.0, 0.5),
    ('KOKC', 'HIGH', 12): (1.0, 0.5),
    ('KOKC', 'LOW',  1): (4.0, 0.0),
    ('KOKC', 'LOW',  2): (4.0, -0.5),
    ('KOKC', 'LOW',  3): (4.0, 0.0),
    ('KOKC', 'LOW',  4): (4.0, 0.0),
    ('KOKC', 'LOW',  5): (3.5, 0.5),
    ('KOKC', 'LOW',  6): (1.0, 0.5),
    ('KOKC', 'LOW',  7): (1.5, 0.0),
    ('KOKC', 'LOW',  8): (2.5, 0.5),
    ('KOKC', 'LOW',  9): (2.5, 0.0),
    ('KOKC', 'LOW', 10): (4.0, 0.0),
    ('KOKC', 'LOW', 11): (4.0, 0.0),
    ('KOKC', 'LOW', 12): (3.0, 0.0),
    # --- KPHL ---
    ('KPHL', 'HIGH',  1): (2.5, 0.0),
    ('KPHL', 'HIGH',  2): (2.0, 0.0),
    ('KPHL', 'HIGH',  3): (1.5, -0.5),
    ('KPHL', 'HIGH',  4): (1.0, -0.5),
    ('KPHL', 'HIGH',  5): (1.0, -0.5),
    ('KPHL', 'HIGH',  6): (1.0, -0.5),
    ('KPHL', 'HIGH',  7): (1.5, 0.0),
    ('KPHL', 'HIGH',  8): (1.5, -0.5),
    ('KPHL', 'HIGH',  9): (1.0, -0.5),
    ('KPHL', 'HIGH', 10): (1.5, 0.0),
    ('KPHL', 'HIGH', 11): (1.5, 0.0),
    ('KPHL', 'HIGH', 12): (2.0, 0.0),
    ('KPHL', 'LOW',  1): (4.0, 0.0),
    ('KPHL', 'LOW',  2): (4.0, 0.5),
    ('KPHL', 'LOW',  3): (3.5, -0.5),
    ('KPHL', 'LOW',  4): (3.0, 0.0),
    ('KPHL', 'LOW',  5): (3.0, 0.5),
    ('KPHL', 'LOW',  6): (3.5, 0.0),
    ('KPHL', 'LOW',  7): (3.5, 0.5),
    ('KPHL', 'LOW',  8): (3.0, 0.5),
    ('KPHL', 'LOW',  9): (3.5, 0.0),
    ('KPHL', 'LOW', 10): (4.0, 0.0),
    ('KPHL', 'LOW', 11): (4.0, 0.0),
    ('KPHL', 'LOW', 12): (4.0, 0.0),
    # --- KPHX ---
    ('KPHX', 'HIGH',  1): (1.0, 0.0),
    ('KPHX', 'HIGH',  2): (1.0, 0.0),
    ('KPHX', 'HIGH',  3): (1.0, -0.5),
    ('KPHX', 'HIGH',  4): (1.5, -0.5),
    ('KPHX', 'HIGH',  5): (1.0, -0.5),
    ('KPHX', 'HIGH',  6): (2.0, -0.5),
    ('KPHX', 'HIGH',  7): (1.0, -0.5),
    ('KPHX', 'HIGH',  8): (1.0, -0.5),
    ('KPHX', 'HIGH',  9): (1.0, 0.0),
    ('KPHX', 'HIGH', 10): (1.0, 0.0),
    ('KPHX', 'HIGH', 11): (1.0, 0.5),
    ('KPHX', 'HIGH', 12): (1.0, 0.0),
    ('KPHX', 'LOW',  1): (2.5, 0.0),
    ('KPHX', 'LOW',  2): (2.5, 0.0),
    ('KPHX', 'LOW',  3): (1.0, 0.0),
    ('KPHX', 'LOW',  4): (2.0, 0.0),
    ('KPHX', 'LOW',  5): (1.0, 0.0),
    ('KPHX', 'LOW',  6): (0.5, 0.0),
    ('KPHX', 'LOW',  7): (2.0, 0.0),
    ('KPHX', 'LOW',  8): (3.5, 0.0),
    ('KPHX', 'LOW',  9): (3.0, -0.5),
    ('KPHX', 'LOW', 10): (2.0, -0.5),
    ('KPHX', 'LOW', 11): (2.0, 0.0),
    ('KPHX', 'LOW', 12): (2.5, 0.5),
    # --- KSAT ---
    ('KSAT', 'HIGH',  8): (1.0, 0.0),
    ('KSAT', 'LOW',  1): (4.0, 0.0),
    ('KSAT', 'LOW',  2): (3.5, 0.0),
    ('KSAT', 'LOW',  3): (4.0, 0.0),
    ('KSAT', 'LOW',  4): (3.0, 0.5),
    ('KSAT', 'LOW',  5): (4.0, 0.0),
    ('KSAT', 'LOW',  6): (3.0, -0.5),
    ('KSAT', 'LOW',  7): (2.0, 1.0),
    ('KSAT', 'LOW',  8): (4.0, -0.5),
    ('KSAT', 'LOW',  9): (4.0, 0.0),
    ('KSAT', 'LOW', 10): (3.5, 0.0),
    ('KSAT', 'LOW', 11): (4.0, 0.0),
    ('KSAT', 'LOW', 12): (4.0, -0.5),
    # --- KSEA ---
    ('KSEA', 'HIGH',  1): (3.0, 0.0),
    ('KSEA', 'HIGH',  2): (2.5, 0.0),
    ('KSEA', 'HIGH',  3): (2.0, 0.5),
    ('KSEA', 'HIGH',  4): (1.5, -0.5),
    ('KSEA', 'HIGH',  5): (1.5, -0.5),
    ('KSEA', 'HIGH',  8): (0.5, 0.0),
    ('KSEA', 'HIGH',  9): (1.0, -0.5),
    ('KSEA', 'HIGH', 10): (2.0, -0.5),
    ('KSEA', 'HIGH', 11): (3.0, 0.0),
    ('KSEA', 'HIGH', 12): (1.5, 0.5),
    ('KSEA', 'LOW',  1): (2.5, 1.0),
    ('KSEA', 'LOW',  2): (3.5, -1.5),
    ('KSEA', 'LOW',  3): (4.0, 0.0),
    ('KSEA', 'LOW',  4): (3.5, 0.0),
    ('KSEA', 'LOW',  5): (3.5, 0.0),
    ('KSEA', 'LOW',  6): (3.5, -0.5),
    ('KSEA', 'LOW',  7): (2.5, 0.0),
    ('KSEA', 'LOW',  8): (0.5, 1.0),
    ('KSEA', 'LOW',  9): (0.5, 0.0),
    ('KSEA', 'LOW', 10): (3.0, 0.5),
    ('KSEA', 'LOW', 11): (4.0, 0.0),
    ('KSEA', 'LOW', 12): (3.0, 0.5),
    # --- KSFO ---
    ('KSFO', 'HIGH',  1): (1.5, 0.0),
    ('KSFO', 'HIGH',  2): (1.0, -0.5),
    ('KSFO', 'HIGH',  3): (0.5, 1.0),
    ('KSFO', 'HIGH',  5): (1.5, 0.0),
    ('KSFO', 'HIGH',  7): (1.0, 0.0),
    ('KSFO', 'HIGH',  9): (1.5, -0.5),
    ('KSFO', 'HIGH', 10): (2.0, 0.0),
    ('KSFO', 'HIGH', 11): (2.0, -0.5),
    ('KSFO', 'HIGH', 12): (1.5, 0.5),
    ('KSFO', 'LOW',  1): (3.0, 0.5),
    ('KSFO', 'LOW',  2): (2.5, 0.0),
    ('KSFO', 'LOW',  3): (3.5, 0.5),
    ('KSFO', 'LOW',  4): (2.0, 0.5),
    ('KSFO', 'LOW',  5): (2.0, 0.5),
    ('KSFO', 'LOW',  6): (1.0, 0.0),
    ('KSFO', 'LOW',  7): (2.5, -1.0),
    ('KSFO', 'LOW',  8): (1.0, 0.0),
    ('KSFO', 'LOW',  9): (2.5, 0.5),
    ('KSFO', 'LOW', 10): (3.5, -1.0),
    ('KSFO', 'LOW', 11): (2.5, 0.0),
    ('KSFO', 'LOW', 12): (3.5, -0.5),
}

# Gaps:
#   KAUS HIGH mo= 3  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.08
#   KAUS HIGH mo= 6  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.69
#   KAUS HIGH mo= 9  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.90
#   KDEN HIGH mo= 7  reason=out_of_bounds before=0.5 after=-0.5 width=0.00 best_mae=1.04
#   KDEN HIGH mo= 8  reason=out_of_bounds before=0.5 after=-0.5 width=0.00 best_mae=0.99
#   KDFW HIGH mo= 2  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.81
#   KDFW HIGH mo= 3  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.80
#   KDFW HIGH mo=10  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.61
#   KDFW HIGH mo=11  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=0.84
#   KDFW HIGH mo=12  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.65
#   KLAS HIGH mo= 3  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=0.86
#   KLAS HIGH mo= 4  reason=out_of_bounds before=0.5 after=-0.5 width=0.00 best_mae=0.84
#   KLAS HIGH mo= 5  reason=out_of_bounds before=0.5 after=-0.5 width=0.00 best_mae=0.90
#   KLAX HIGH mo= 2  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=1.49
#   KLAX LOW  mo= 3  reason=out_of_bounds before=3.5 after=-3.5 width=0.00 best_mae=1.39
#   KLAX LOW  mo= 5  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=0.84
#   KLAX HIGH mo=11  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.51
#   KMDW HIGH mo= 3  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.62
#   KMDW HIGH mo= 4  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.36
#   KMDW HIGH mo= 5  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=1.27
#   KMDW HIGH mo= 6  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=1.05
#   KMDW HIGH mo= 7  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.03
#   KMDW HIGH mo=10  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.81
#   KMSP HIGH mo= 2  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.00
#   KMSP HIGH mo= 4  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.87
#   KMSP HIGH mo= 5  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.94
#   KMSP HIGH mo= 6  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.84
#   KMSP LOW  mo= 8  reason=out_of_bounds before=3.5 after=-3.5 width=0.00 best_mae=1.54
#   KMSP HIGH mo= 9  reason=out_of_bounds before=-0.0 after=0.0 width=0.00 best_mae=0.85
#   KMSP HIGH mo=10  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.60
#   KMSY HIGH mo= 5  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.80
#   KMSY HIGH mo= 6  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.92
#   KMSY HIGH mo= 9  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=0.73
#   KMSY HIGH mo=10  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.86
#   KNYC HIGH mo= 8  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=1.08
#   KNYC HIGH mo= 9  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.67
#   KNYC HIGH mo=10  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.09
#   KOKC HIGH mo= 3  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.18
#   KOKC HIGH mo= 8  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=1.01
#   KOKC HIGH mo=10  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.09
#   KSAT HIGH mo= 1  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=0.81
#   KSAT HIGH mo= 2  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.65
#   KSAT HIGH mo= 3  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.92
#   KSAT HIGH mo= 4  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.60
#   KSAT HIGH mo= 5  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.78
#   KSAT HIGH mo= 6  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.69
#   KSAT HIGH mo= 7  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.76
#   KSAT HIGH mo= 9  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.79
#   KSAT HIGH mo=10  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=0.70
#   KSAT HIGH mo=11  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=0.80
#   KSAT HIGH mo=12  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=0.65
#   KSEA HIGH mo= 6  reason=out_of_bounds before=0.5 after=-0.5 width=0.00 best_mae=1.12
#   KSEA HIGH mo= 7  reason=out_of_bounds before=0.5 after=-0.5 width=0.00 best_mae=0.82
#   KSFO HIGH mo= 4  reason=out_of_bounds before=-0.5 after=1.0 width=0.50 best_mae=1.73
#   KSFO HIGH mo= 6  reason=out_of_bounds before=0.5 after=-0.5 width=0.00 best_mae=1.37
#   KSFO HIGH mo= 8  reason=out_of_bounds before=-1.0 after=1.0 width=0.00 best_mae=1.30

# Diagnostics (best offset, best mae, settled at best, window):
#   KATL HIGH  1  best_offset=+0.00 best_mae=1.70  settled_at_best=0.52  window_offsets=[-1.00,+0.00]  width=1.00h
#   KATL LOW   1  best_offset=-2.00 best_mae=2.70  settled_at_best=0.29  window_offsets=[-4.00,-0.50]  width=3.50h
#   KATL HIGH  2  best_offset=-0.50 best_mae=1.44  settled_at_best=0.34  window_offsets=[-1.00,+0.00]  width=1.00h
#   KATL LOW   2  best_offset=-2.00 best_mae=2.88  settled_at_best=0.29  window_offsets=[-4.00,+0.00]  width=4.00h
#   KATL HIGH  3  best_offset=-1.00 best_mae=1.49  settled_at_best=0.28  window_offsets=[-1.50,+0.00]  width=1.50h
#   KATL LOW   3  best_offset=-1.00 best_mae=2.24  settled_at_best=0.30  window_offsets=[-3.50,+0.00]  width=3.50h
#   KATL HIGH  4  best_offset=-0.50 best_mae=1.10  settled_at_best=0.34  window_offsets=[-1.50,+0.00]  width=1.50h
#   KATL LOW   4  best_offset=-1.00 best_mae=1.81  settled_at_best=0.27  window_offsets=[-3.00,+0.00]  width=3.00h
#   KATL HIGH  5  best_offset=-0.50 best_mae=1.00  settled_at_best=0.38  window_offsets=[-1.00,-0.50]  width=0.50h
#   KATL LOW   5  best_offset=+0.50 best_mae=1.12  settled_at_best=0.53  window_offsets=[-1.50,+0.50]  width=2.00h
#   KATL HIGH  6  best_offset=-0.50 best_mae=1.04  settled_at_best=0.37  window_offsets=[-1.50,+0.00]  width=1.50h
#   KATL LOW   6  best_offset=-0.50 best_mae=1.00  settled_at_best=0.41  window_offsets=[-2.00,+0.00]  width=2.00h
#   KATL HIGH  7  best_offset=-0.50 best_mae=1.08  settled_at_best=0.35  window_offsets=[-1.50,+0.00]  width=1.50h
#   KATL LOW   7  best_offset=-0.50 best_mae=1.01  settled_at_best=0.38  window_offsets=[-3.00,+0.00]  width=3.00h
#   KATL HIGH  8  best_offset=+0.00 best_mae=1.05  settled_at_best=0.46  window_offsets=[-1.50,+0.00]  width=1.50h
#   KATL LOW   8  best_offset=+0.00 best_mae=0.96  settled_at_best=0.47  window_offsets=[-2.00,+1.00]  width=3.00h
#   KATL HIGH  9  best_offset=-0.50 best_mae=1.18  settled_at_best=0.31  window_offsets=[-2.00,+0.00]  width=2.00h
#   KATL LOW   9  best_offset=-0.50 best_mae=1.09  settled_at_best=0.34  window_offsets=[-2.00,+0.50]  width=2.50h
#   KATL HIGH 10  best_offset=-0.50 best_mae=1.04  settled_at_best=0.34  window_offsets=[-1.00,-0.50]  width=0.50h
#   KATL LOW  10  best_offset=-1.00 best_mae=1.80  settled_at_best=0.29  window_offsets=[-3.00,+0.00]  width=3.00h
#   KATL HIGH 11  best_offset=+0.00 best_mae=1.34  settled_at_best=0.50  window_offsets=[-1.00,+0.00]  width=1.00h
#   KATL LOW  11  best_offset=-3.00 best_mae=2.62  settled_at_best=0.18  window_offsets=[-4.00,-0.50]  width=3.50h
#   KATL HIGH 12  best_offset=+0.00 best_mae=1.46  settled_at_best=0.55  window_offsets=[-1.00,+0.50]  width=1.50h
#   KATL LOW  12  best_offset=-0.50 best_mae=2.62  settled_at_best=0.39  window_offsets=[-4.00,+0.50]  width=4.50h
#   KAUS HIGH  1  best_offset=-0.50 best_mae=1.17  settled_at_best=0.35  window_offsets=[-0.50,+0.50]  width=1.00h
#   KAUS LOW   1  best_offset=-3.00 best_mae=3.75  settled_at_best=0.24  window_offsets=[-4.00,+1.00]  width=5.00h
#   KAUS HIGH  2  best_offset=+0.00 best_mae=1.35  settled_at_best=0.49  window_offsets=[-0.50,+0.50]  width=1.00h
#   KAUS LOW   2  best_offset=-3.00 best_mae=4.00  settled_at_best=0.26  window_offsets=[-4.00,+1.00]  width=5.00h
#   KAUS LOW   3  best_offset=-4.00 best_mae=4.25  settled_at_best=0.18  window_offsets=[-4.00,+1.00]  width=5.00h
#   KAUS HIGH  4  best_offset=+0.00 best_mae=1.02  settled_at_best=0.52  window_offsets=[-1.00,+1.00]  width=2.00h
